spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.name=codinglair-taf
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
spring.ai.mcp.server.capabilities.prompt=true
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
