apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taf-system
resources:
  - namespace.yaml
  - config.yaml
  - mongodb.yaml
  - keycloak.yaml
  - control-plane.yaml
  - worker.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: codinglair-taf
